version: "3"
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  uwf-content-service:
    image: metam-docker-hosted.forge.avaya.com/uwf-content-service:uniclient
    ports:
      - "50000:8080"
    restart: unless-stopped
  uwf-registry:
    image: metam-docker-hosted.forge.avaya.com/uwf-registry-service:0.78.89
    depends_on:
      - "kafka"
    volumes:
        - ./uwf-registry-application.yaml:/etc/config/application.yaml
    ports:
      - "50052:50052"
    restart: unless-stopped
  uwf-api-service:
    depends_on:
      - "kafka"
    image: metam-docker-hosted.forge.avaya.com/uwf-api-service:0.78.23
    volumes:
        - ./uwf-api-service-application.yaml:/etc/config/application.yaml
    ports:
      - "50054:50054"
    depends_on:
      - "kafka"
    restart: unless-stopped  
  uwf-sample-application:
    image: local/uwf-sample-applications:v1 
    depends_on:
      - "uwf-registry"
    ports:
      - "4001:4001"
  api:
    image: local/api:v1 
    depends_on:
      - "uwf-registry"
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
       - /c/Users/nicholasd/.kube:/usr/src/

