service:
  api:
    enabled: "true"
  enable-get-applications-by-audience: "true"
k8watcher:
  enabled: "false"
logging:
  level: "debug"
  format: "UTF-8"
alarming:
  enabled: "false"
kafka:
  enabled: "true"
  version: "2.2.0"
  address: "kafka:29092"
  bootstrap-servers:
    - kafka:29092
  topics:
    applicationDataRegistration: uwf-application-data-registration