export const ADD_USER = 'ADD_USER';
export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const ADD_USER_CANCELLED = 'ADD_USER_CANCELLED';

export const UPDATE_USER = 'UPDATE_USER';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';
export const DELETE_USER_CANCELLED = 'DELETE_USER_CANCELLED';

export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
